### ISSUE TITLE
kitchen converge throws depreciation error.

### ISSUE THREAD

**Issue by saikiran243** [QT-DevOps/DevOpsIssues#120]
trying to install node.js it is throwing error below
iam trying with vagrant as kitchen driver

PS D:\chef-starter\chef-repo\cookbooks\nodejsdeploy> kitchen converge
-----> Starting Kitchen (v1.22.0)
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 16.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=16.04&m=x86_64
         to file /tmp/install.sh.1595/metadata.txt
       trying wget...
       sha1     845b83d65443c62b11911fc83a70d6cac282f7cd
       sha256   f2578ed674189d4c303e5fece3faeb4c4a0117f5d29e5e050982a38fbaaad0e5
       url      https://packages.chef.io/files/stable/chef/14.3.37/ubuntu/16.04/chef_14.3.37-1_amd64.deb
       version  14.3.37
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef_14.3.37-1_amd64.deb exists
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       Installing chef
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 38375 files and directories currently installed.)
       Preparing to unpack .../cache/chef_14.3.37-1_amd64.deb ...
       Unpacking chef (14.3.37-1) ...
       Setting up chef (14.3.37-1) ...
       Thank you for installing Chef!
       Transferring files to <default-ubuntu-1604>
       Starting Chef Client, version 14.3.37
       Creating a new client identity for default-ubuntu-1604 using the validator key.
       resolving cookbooks for run list: ["nodejsdeploy::default"]
       Synchronizing Cookbooks:
         - nodejsdeploy (1.0.0)
         - nodejs (5.0.0)
         - pm2 (0.7.4)
         - build-essential (8.1.1)
         - nginx (8.1.5)
         - ark (4.0.0)
         - poise-javascript (1.1.0)
         - ohai (5.2.3)
         - zypper (0.4.0)
         - yum-epel (3.2.0)
         - mingw (2.1.0)
         - seven_zip (3.0.0)
         - poise (2.8.2)
         - poise-languages (2.1.2)
         - windows (5.0.0)
         - poise-archive (1.5.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 0 resources

       Running handlers:
       Running handlers complete

       Deprecated features used!
         Resource windows_auto_run has been loaded from a cookbook. The resource windows_auto_run is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_auto_run resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_feature has been loaded from a cookbook. The resource windows_feature is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_feature resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_feature_dism has been loaded from a cookbook. The resource windows_feature_dism is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_feature_dism resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_feature_powershell has been loaded from a cookbook. The resource windows_feature_powershell is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_feature_powershell resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_font has been loaded from a cookbook. The resource windows_font is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_font resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_pagefile has been loaded from a cookbook. The resource windows_pagefile is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_pagefile resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_printer has been loaded from a cookbook. The resource windows_printer is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_printer resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_printer_port has been loaded from a cookbook. The resource windows_printer_port is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_printer_port resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource windows_shortcut has been loaded from a cookbook. The resource windows_shortcut is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_shortcut resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource build_essential has been loaded from a cookbook. The resource build_essential is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the build_essential resource. at 1 location:
           - /tmp/kitchen/cache/cookbooks/build-essential/resources/build_essential.rb:20:in `class_from_file'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource ohai_hint has been loaded from a cookbook. The resource ohai_hint is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the ohai_hint resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.
         Resource zypper_repo has been loaded from a cookbook. The resource zypper_repo is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the zypper_repo resource. at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
          See https://docs.chef.io/deprecations_map_collision.html for further details.

       Chef Client finished, 0/0 resources updated in 04 seconds
       Downloading files from <default-ubuntu-1604>
       Finished converging <default-ubuntu-1604> (1m54.50s).

can any one help me how to overcome it. thanks in advance

**Comment by saikiran243** [comment]
at the time of berks install got this as output
PS D:\chef-starter\chef-repo\cookbooks\nodejsdeploy> berks install
Resolving cookbook dependencies...
Fetching 'nodejsdeploy' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Installing ark (4.0.0)
Installing build-essential (8.1.1)
Installing mingw (2.1.0)
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-archive-0.4.6/lib/mixlib/archive/lib_archive.rb:23: warning: conflicting chdir during another chdir block
Installing nginx (8.1.5)
Installing nodejs (5.0.0)
Using nodejsdeploy (1.0.0) from source at .
Installing ohai (5.2.3)
Installing pm2 (0.7.4)
Installing poise (2.8.2)
Installing poise-archive (1.5.0)
Installing poise-javascript (1.1.0)
Installing poise-languages (2.1.2)
Installing seven_zip (3.0.0)
Using windows (5.0.0)
Installing yum-epel (3.2.0)
Installing zypper (0.4.0)
Cookbook 'build-essential' (8.1.1) not found in any of the sources!

when tried again it showed all above packages are installed.

tried to change the kitchen.yml to ignore the errors as

provisioner:
  name: chef_solo
  solo_rb:
  treat_deprecation_warnings_as_errors: true
  silence_deprecation_warnings:
        - windows_auto_run
        - windows_feature 
        - windows_feature_dism
        - windows_feature_powershell
        - windows_font
        - windows_pagefile 
        - windows_printer
        - windows_printer_port
        - build_essential 
        - zypper_repo 
        - ohai_hint 
        - windows_shortcut

still it is not solved

**Comment by saikiran243** [comment]
Sol: pm2 has dependencies which are depreciated hence it doesnt work
