### ISSUE TITLE
Job Failing on Jenkins Server(Ubuntu)

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#166]
Hi Team,

I have followed all steps to configure Jenkins on Ubuntu instance.
When a  new item is saved to run any job it is failing(multiple times)
Checked java -version on Ubuntu Server.

ubuntu@ip-172-31-88-32:~$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Below is the console output after job failed.
Console Output
Started by user AamuktaUbuntu
Building in workspace /var/lib/jenkins/workspace/Team-A-Daybuild
[WS-CLEANUP] Deleting project workspace...
Cloning the remote Git repository
Cloning repository https://github.com/asquarezone/spring-petclinic.git
 > git init /var/lib/jenkins/workspace/Team-A-Daybuild # timeout=10
Fetching upstream changes from https://github.com/asquarezone/spring-petclinic.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/asquarezone/spring-petclinic.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/asquarezone/spring-petclinic.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/asquarezone/spring-petclinic.git # timeout=10
Fetching upstream changes from https://github.com/asquarezone/spring-petclinic.git
 > git fetch --tags --progress https://github.com/asquarezone/spring-petclinic.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision dbdadaa2cc5380e6cf9bdedb20cf839ef32c82e5 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f dbdadaa2cc5380e6cf9bdedb20cf839ef32c82e5
Commit message: "Added mail feature"
First time build. Skipping changelog.
[Team-A-Daybuild] $ mvn package
FATAL: command execution failed
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Caused: java.io.IOException: Cannot run program "mvn" (in directory "/var/lib/jenkins/workspace/Team-A-Daybuild"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at hudson.Launcher$ProcStarter.join(Launcher.java:465)
	at hudson.tasks.Maven.perform(Maven.java:367)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by arunkumar127** [comment]
$ mvn package
Command execution failed.
Is Maven installed in Ubuntu Server? Have you set Maven Environment variables?
![screenshot_2018-09-16-18-09-05](https://user-images.githubusercontent.com/40756184/45596609-ebcf2e00-b9db-11e8-8469-33a5ec13ef55.jpeg)

**Comment by Aamukta** [comment]
> $ mvn package
> Command execution failed.
> Is Maven installed in Ubuntu Server? Have you set Maven Environment variables?
> ![screenshot_2018-09-16-18-09-05](https://user-images.githubusercontent.com/40756184/45596609-ebcf2e00-b9db-11e8-8469-33a5ec13ef55.jpeg)

Hi Arun,

Thanks for assisting me.
I have cross checked maven envi variables and found that the version entered in /etc/profile were incorrect.
Now I am able to run job on Jenkins
