### ISSUE TITLE
SonarQube issue while creating Pipeline project. 

### ISSUE THREAD

**Issue by VenkateswararaoPaturi** [QT-DevOps/DevOpsIssues#177]
I have setup jenkins in my local machine along with Maven and SonarQube and Sonar Runner. I am able to login Sonar with localhost:9000.

1. Added Sonar Scanner plugin into Jenkins 
2. Configured Sonar Qube Server
 Manage jenkins -->Configure System see the bellow screenshot 
![image](https://user-images.githubusercontent.com/42858804/45917420-5e388600-be94-11e8-88fc-032baeb64572.png)
 3. Configured Sonar Scanner with global tool configured configuration .
Manage Jenkins--> Global Tool configuration.

![image](https://user-images.githubusercontent.com/42858804/45917440-dc952800-be94-11e8-883d-4a350e11aef0.png)
4. Created pipeline job with script. below is the script.

node {
    stage('SCM') {
        git 'https://github.com/asquarezone/game-of-life.git'
    }
    
    stage('Build & Package') {
        withSonarQubeEnv('sonar') {
            sh 'mvn clean package sonar:sonar'
        }
    }
    
     stage('Results'){
        archive 'gameoflife-web/target/gameoflife.war'
        junit 'gameoflife-web/target/surefire-reports/*.xml'
    }
}

5. After Building project getting error. Below is the error log.

hudson.remoting.ProxyException: hudson.AbortException: SonarQube installation defined in this job (sonar) does not match any configured installation. Number of installations that can be configured: 1.
If you want to reassign jobs to a different SonarQube installation, check the documentation under https://redirect.sonarsource.com/plugins/jenkins.html
	at hudson.plugins.sonar.SonarInstallation.checkValid(SonarInstallation.java:92)
	at hudson.plugins.sonar.SonarBuildWrapper.setUp(SonarBuildWrapper.java:65)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution.start(CoreWrapperStep.java:80)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:229)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: hudson.AbortException: SonarQube installation defined in this job (sonar) does not match any configured installation. Number of installations that can be configured: 1.
If you want to reassign jobs to a different SonarQube installation, check the documentation under https://redirect.sonarsource.com/plugins/jenkins.html
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.replay(CpsStepContext.java:499)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:258)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeDescribable(DSL.java:358)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:156)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 

Please suggest what may casuing issue.

**Comment by arunkumar127** [comment]
@VenkateswararaoPaturi 
As you have set Sonar name as **SonarQube**

Build & Package stage should be
stage('Build & Package') {
    **withSonarQubeEnv('SonarQube')** {
        sh 'mvn clean package sonar:sonar'
    }
}

Mention exact name which you have given for Sonar.

**Comment by VenkateswararaoPaturi** [comment]
@arunkumar127 
After updating sonar value reeving the below error . 

Commit message: "Added sonarqube integration"
 > C:\Program Files\Git\bin\git.exe rev-list --no-walk 0cb6abb8af23cfc0e37565c25b15b3ffd529e5a0 # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build & Package)
[Pipeline] withSonarQubeEnv
Injecting SonarQube environment variables using the configuration: SonarQube
[Pipeline] {
[Pipeline] sh
[C:\Program Files (x86)\Jenkins\workspace\GOL_Pipeline] Running shell script
[Pipeline] }
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: CreateProcess error=2, The system cannot find the file specified

Do i need to add any configuration or files ?

**Comment by raviops100** [comment]
Hi VenkateswaraRao,

in the 2 step of your configuration in jenikins  
server authentication feild it is empty

to get this token  once you log in in sonarqube top right corner has go to my account security genate token 
give some name click on genarate
that token you need to paste at  authentication feild

in the 3 step of your configuration 

for time being just remove the 3 step 

in pipeline script paste below line try to bulid once 

node {
stage('SCM') {
git 'https://github.com/asquarezone/game-of-life.git'
}

stage('Build & Package') {
    withSonarQubeEnv('SonarQube') {
        sh 'mvn clean package sonar:sonar'
    }
}

Thanks
Ravi

**Comment by raviops100** [comment]
in the 3 step of your configuration

Configured Sonar Scanner with global tool configured configuration .
Manage Jenkins--> Global Tool configuration.

SonarQube Scanner just click on install auomatically

just remove sonar runner all of that try to build

**Comment by VenkateswararaoPaturi** [comment]
@raviops100

I have updated the suggested changes but still getting same error. 

WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: CreateProcess error=2, The system cannot find the file specified

Caused: java.io.IOException: Cannot run program "nohup" (in directory "C:\Program Files (x86)\Jenkins\workspace\GOL_Pipeline"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:929)
	at hudson.Launcher$ProcStarter.start(Launcher.java:449)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:186)

**Comment by raviops100** [comment]
Hi Venkateswararao,

which environment you have installed jenkins and sonarQube windows (or) LINUX ???

Thanks
Ravi

**Comment by VenkateswararaoPaturi** [comment]
@raviops100  @arunkumar127 

I am using windows 10 , SonarQube 5.6.7  and jenkins 2.138

Thanks
Venkat

**Comment by raviops100** [comment]
Hi Venkateswarao,

The `sh` step is not supported on the Windows platform

1. C:\Program Files\Git\bin is in the global search path, such that Jenkins finds sh.exe

2. Jenkins also needs nohup.exe  
3. Git-bash has a nohup.exe in /usr/bin.  just symlinked that  into /bin 

Please run below commands  from a Windows cmd prompt(or) powershell run as admin:

mklink "C:\Program Files\Git\bin\nohup.exe" "C:\Program Files\git\usr\bin\nohup.exe"
mklink "C:\Program Files\Git\bin\msys-2.0.dll" "C:\Program Files\git\usr\bin\msys-2.0.dll"
mklink "C:\Program Files\Git\bin\msys-iconv-2.dll" "C:\Program Files\git\usr\bin\msys-iconv-2.dll"
mklink "C:\Program Files\Git\bin\msys-intl-8.dll" "C:\Program Files\git\usr\bin\msys-intl-8.dll"

Hope this will work 

Thanks
Ravi

**Comment by VenkateswararaoPaturi** [comment]
@raviops100 

I have already symlinked into bin below is the output if i run the same command again.

C:\WINDOWS\system32>mklink "C:\Program Files\Git\bin\nohup.exe" "C:\Program Files\git\usr\bin\nohup.exe"
Cannot create a file when that file already exists.

C:\WINDOWS\system32>mklink "C:\Program Files\Git\bin\msys-2.0.dll" "C:\Program Files\git\usr\bin\msys-2.0.dll"
Cannot create a file when that file already exists.

Console output from Jenkins. Please check if i am missing anything or doing anything wrong. 
----------------------------------------------------------------------------------------------------------
Running on Jenkins in C:\Program Files (x86)\Jenkins\workspace\GOL_Complete_Pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (SCM)
[Pipeline] git
 > C:\Program Files\Git\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/asquarezone/game-of-life.git # timeout=10
Fetching upstream changes from https://github.com/asquarezone/game-of-life.git
 > C:\Program Files\Git\bin\git.exe --version # timeout=10
 > C:\Program Files\Git\bin\git.exe fetch --tags --progress https://github.com/asquarezone/game-of-life.git +refs/heads/*:refs/remotes/origin/*
 > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 0cb6abb8af23cfc0e37565c25b15b3ffd529e5a0 (refs/remotes/origin/master)
 > C:\Program Files\Git\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Program Files\Git\bin\git.exe checkout -f 0cb6abb8af23cfc0e37565c25b15b3ffd529e5a0
 > C:\Program Files\Git\bin\git.exe branch -a -v --no-abbrev # timeout=10
 > C:\Program Files\Git\bin\git.exe branch -D master # timeout=10
 > C:\Program Files\Git\bin\git.exe checkout -b master 0cb6abb8af23cfc0e37565c25b15b3ffd529e5a0
Commit message: "Added sonarqube integration"
 > C:\Program Files\Git\bin\git.exe rev-list --no-walk 0cb6abb8af23cfc0e37565c25b15b3ffd529e5a0 # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build & Package)
[Pipeline] withSonarQubeEnv
Injecting SonarQube environment variables using the configuration: SonarQube
[Pipeline] {
[Pipeline] sh
[C:\Program Files (x86)\Jenkins\workspace\GOL_Complete_Pipeline] Running shell script
[Pipeline] }
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:929)
	at hudson.Launcher$ProcStarter.start(Launcher.java:449)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:186)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:86)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:182)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:229)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:153)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
Caused: java.io.IOException: Cannot run program "nohup" (in directory "C:\Program Files (x86)\Jenkins\workspace\GOL_Complete_Pipeline"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)

Thanks
Venkat

**Comment by raviops100** [comment]
Hi Venkat,
Can you please try the same task on linux OS ubuntu (or) redhat
Thanks
Ravi

**Comment by rishimallik12** [comment]
> @VenkateswararaoPaturi
> As you have set Sonar name as **SonarQube**
> 
> Build & Package stage should be
> stage('Build & Package') {
> **withSonarQubeEnv('SonarQube')** {
> sh 'mvn clean package sonar:sonar'
> }
> }
> 
> Mention exact name which you have given for Sonar.

Its working for me thank you for ur valuable info

**Comment by rishimallik12** [comment]
thank you
