### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/DevOpsIssues#436]
While i am trying build in pipeline project, i am getting this error, please let me know how to fix it.

java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:173)
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:165)
	at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
	at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:165)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:110)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by bhaskardegala** [comment]
Can please show us your groove script please

**Comment by sandeep5683** [comment]
i am doing it through pipeline script from SCM

**Comment by sandeep5683** [comment]
node('MVN'){

    stage('GIT'){
      git branch: 'Dev', url: 'https://github.com/sandeep5683/spring-petclinic-1.git'  
    }
    stage('Build'){
        sh 'mvn package'
    }
}

**Comment by bhaskardegala** [comment]
I think it could not find the file , as Linux is case sensitive make sure that file name "Jenkinsfile" J is capital and let me know the update

**Comment by sandeep5683** [comment]
nope not working

**Comment by nagireddy-9** [comment]
please share full logfile

**Comment by sandeep5683** [comment]
Started by user Sandeep.sanapala
java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:173)
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:165)
	at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
	at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:165)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:110)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by bhaskardegala** [comment]
Can please show few screen shot of config project page and actually it was stating file was not found so we can find some related details from that page

**Comment by dharmatejadevops** [comment]
> node('MVN'){
> 
> ```
> stage('GIT'){
>   git branch: 'Dev', url: 'https://github.com/sandeep5683/spring-petclinic-1.git'  
> }
> stage('Build'){
>     sh 'mvn package'
> }
> ```
> 
> }

is label 'MVN' , that node  

> node('MVN'){
> 
> ```
> stage('GIT'){
>   git branch: 'Dev', url: 'https://github.com/sandeep5683/spring-petclinic-1.git'  
> }
> stage('Build'){
>     sh 'mvn package'
> }
> ```
> 
> }

hi sandeep i can run with your pipeline on my Jenkins not getting any error its working. 

did you install maven on your node .

**Comment by Meganathreddy** [comment]
> Started by user Sandeep.sanapala
> java.io.FileNotFoundException
> at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:173)
> at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:165)
> at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
> at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
> at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
> at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
> at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:165)
> at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
> at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:110)
> at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
> at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
> at hudson.model.ResourceController.execute(ResourceController.java:97)
> at hudson.model.Executor.run(Executor.java:429)
> Finished: FAILURE

Hello,
I got the same issue before couple of days. and the root cause is the incorrect naming convenction of "Jenkinsfile". So please make sure the file which you created in git repository is provided in jenkins->Project->configure-> Build -> Pipeline script from SCM-> "Jenkinsfile".

Also, you need to make sure, JDK & Maven are installed on the node and declare the environment variables. 
Create a jenkins user on the node and enable sudo permission and SSH authentication permission.
Check the connectivity between master and node using SSH and then Integrate node with jenkins master.

**Comment by shaikkhajaibrahim** [comment]
Please retry jenkins installation & try this when all the plugins have installed
