### ISSUE TITLE
Issue with docker-compose

### ISSUE THREAD

**Issue by kiranmaikota** [QT-DevOps/DevOpsIssues#834]
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1077, in up
  File "compose/cli/main.py", line 1073, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 355, in ensure_image_exists
  File "compose/service.py", line 381, in image
  File "site-packages/docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[50048] Failed to execute script docker-compose

Facing the above error when executing docker-compose up. Any hints please

**Comment by kiranmaikota** [comment]
found that required configuration which is mentioned in docker-compose file is missing
